[tool.poetry]
name = "shapefiles"
version = "0.1.0"
description = "This project will contain codes for creating LGD Mapping to shapefiles."
authors = ["Surya Kandukuri"]

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = "^0.13.0"
click = "^7.1.2"
pandas = "^1.0.5"
numpy = "^1.19.0"
pyshp = "^2.1.3"
matplotlib = "^3.4.2"
gdal = {path = "geopandas-dependencies/GDAL-3.3.0-cp39-cp39-win_amd64.whl"}
pyproj = {path = "geopandas-dependencies/pyproj-3.1.0-cp39-cp39-win_amd64.whl"}
fiona = {path = "geopandas-dependencies/Fiona-1.8.20-cp39-cp39-win_amd64.whl"}
shapely = {path = "geopandas-dependencies/Shapely-1.7.1-cp39-cp39-win_amd64.whl"}
geopandas = {path = "geopandas-dependencies/geopandas-0.9.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
