[tool.poetry]
name = "library"
version = "0.1.0"
description = ""
authors = ["Surya Kandukuri <surya_kandukuri@isb.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"